### PR TITLE
Add unit tests and code coverage

### PR DESCRIPTION
**Pull request by jkernech**
The code coverage is 95.5%. Unfortunately, it's not 100% since I couldn't find a way to test the client connection errors.

### CODE REVIEW

**Comment by mariostesla** [comment]
easiest way to get redis client connection errors is if the password is wrong but since there is no password here maybe you can try setting a wrong port number

**Comment by mariostesla** [comment]
you have to add an event listener, something like this
```
redisCache.store.events.on('redisError', function(err) {
    expect(err).not.toBe(null);
    done();
});
```
but the `done()` might be called multiple times, but since this is the last test it might not be a problem, i don't know :p

**Comment by jkernech** [comment]
Thanks for your feedback @mariostesla ! 

The main issue there is related to the fact that I can't simulate/reproduce a Redis connection error. I used the same code as the one you suggest at the beginning but it throws a timeout (jasmine).. The latest percentage are also related to this issue : I can't generate a connection error via the `connect` method :

```
function connect(cb) {
    pool.acquire(function(err, conn) {
      if (err) {
        pool.release(conn);
        return cb(err);
      }
 
      if (args.db || args.db === 0) {
        conn.select(args.db);
      }
 
      cb(null, conn);
    });
  }
```


I'll be glad to hear from you more suggestions :)

**Comment by mariostesla** [comment]
i modified the last test like this
```
    redisCache = require('cache-manager').caching({
      store: redisStore,
      host: '127.0.0.10',
      port: config.redis.port,
      db: config.redis.db,
      connect_timeout: 1
    });

    redisCache.set('foo', 'bar', function(err) {});
    redisCache.store.events.on('redisError', function(error) {
      expect(error).not.toBe(null);
      console.log(error);
      done();
    });
```
i couldn't run the coverage (because of windows i suppose...) but i added the console log at the event and it printed the error.

i don't know about the connect function though

**Comment by jkernech** [comment]
@mariostesla Indeed, this is the right way to test the redis error event. I will update my code with your suggestion. Now, I have to find a way to test the `connect` error message. Thanks !


PS, the callbacks are now optional :

```
redisCache.set('foo', 'bar', function(err) {});
```
```
redisCache.set('foo', 'bar');
```

**Pull request merged**
