### PR TITLE
Refactor/use mocha

### PR DESCRIPTION
**Pull request by PuKoren**
Use mocha instead of Jasmine and fix latent regression (specs not implemented revealed by switch to mocha)

Following our conversation on #45 

@dial-once/developers

### CODE REVIEW

**Comment by mrister** [comment]
LGTM! let's kick that jasmine out!

**Comment by PuKoren** [comment]
I wonder how jasmine specs can run without this piece of code: https://github.com/dial-once/node-cache-manager-redis/pull/46/files#diff-168726dbe96b3ce427e7fedce31bb0bcR191. Test concerned is `set > should not store an invalid value`

**Comment by mrister** [comment]
@PuKoren I have no clue and it's far to late to be thinking straight :-)

**Comment by mrister** [comment]
@PuKoren maybe because of jasmines .notToBe https://github.com/adobe/brackets/issues/5479

**Comment by PuKoren** [comment]
@mrister good catch

**Comment by jkernech** [comment]
LGTM

**Pull request merged**
