### PR TITLE
Updating to sol-redis-pool 0.3.1.

### PR DESCRIPTION
**Pull request by afrasso**
Updating to latest version of sol-redis-pool.

### CODE REVIEW

**Comment by afrasso** [comment]
@mrister Does this help accomplish issue #39?

**Comment by afrasso** [comment]
sol-redis-pool 0.3.1 contains a fix for reconnecting to a redis server after a disconnection. I'm hoping to get this merged as soon as possible. @mihovilrister @mrister @mariostesla @cludden (not sure who the admins are)

**Comment by afrasso** [comment]
Any update on this? If it shouldn't be merged can I get some feedback?

**Comment by mrister** [comment]
@afrasso sorry for the lack of feedback. Will be handled via https://github.com/dial-once/node-cache-manager-redis/pull/42 Thank you for the contribution!

**Comment by afrasso** [comment]
Thanks! Any idea on when the new version will be released?

**Comment by afrasso** [comment]
@mrister Any update on releasing a new version?

**Comment by mrister** [comment]
@afrasso Sorry but I don't have a concrete date to tell you, we are waiting on some other PRS to test and get merged so we have more significant release.

**Comment by afrasso** [comment]
@mrister That's okay. In the meantime we're blocked on deploying our caching while waiting for that fix to sol-redis-pool. Any idea if we're talking a few days, or a few weeks? Depending on the answer will change how we'll proceed for now.

**Comment by mrister** [comment]
@afrasso We will release a new version today!

**Comment by afrasso** [comment]
@mrister THANK YOU!!!!

**Comment by mrister** [comment]
@afrasso  New version is released and on NPM https://github.com/dial-once/node-cache-manager-redis/releases/tag/v0.2.4

**Pull request closed without merging**
